config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  get '/questions/recent' => 'questions#recent'
  get '/questions/trending' => 'questions#trending'
  get '/questions/most_votes' => 'questions#index'

  resources :questions
  resources :comments
  resources :answers

  resources :users
  post '/users/login' => 'users#login'
  delete '/users/logout' => 'users#logout'

  post '/questions/upvote' => 'questions#upvote'
  post '/questions/downvote' => 'questions#downvote'

  post '/answers/upvote' => 'answers#upvote'
  post '/answers/downvote' => 'answers#downvote'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voteable
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  has_many :answers
  has_one :best_answer, class_name: "Answer"
  validates_presence_of :title, :content
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ApplicationHelper

  def index
    @questions = Question.all.to_a.sort_by(&:votes_count).reverse
    if request.xhr?
      render :river
    else
      render :index
    end
  end

  def recent
    @questions = Question.order('created_at DESC')
    if request.xhr?
      render :river
    else
      render :index
    end  
  end

  def trending
    @questions = Question.order('votes_count DESC')
    if request.xhr?
      render :river
    else
      render :index
    end 
  end

  def show
    @question = Question.find_by(id: params[:id])
    @answer = Answer.new
  end

  def new
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    @question = Question.new()
  end

  def create
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    user = current_user
    @question = user.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      flash[:error] = @question.errors.full_messages
      render :new
    end
  end

  def edit
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    @question = Question.find_by(id: params[:id])
  end

  def update
    @question = Question.find_by(id: params[:id])

    if @question.update_attributes(question_params)
      redirect_to @question
    else
      flash[:error] = @question.errors.full_messages
      render :edit
    end

  end

  def destroy
    @question = Question.find_by(id: params[:id])
    @question.destroy
    redirect_to questions_path
  end

  def upvote
    @question = Question.find_by(id: params[:id])
    unless @question.voted_by_current_user?(voter: current_user, up: true)
      @question.upvote(session[:user_id]) if logged_in?
    end
    unless request.xhr?
      redirect_to :back unless request.xhr?
    else
      render partial: "questions/votes", locals: {question: @question}
    end
  end

  def downvote
    @question = Question.find_by(id: params[:id])
    unless @question.voted_by_current_user?(voter: current_user, up: false)
      @question.downvote(session[:user_id]) if logged_in?
    end
    unless request.xhr?
      redirect_to :back unless request.xhr?
    else
      render partial: "questions/votes", locals: {question: @question}
    end
  end


  private

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def vote_params
    params.require(:vote).permit(:up_or_down)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.erb
  <li class="answer-display">
      <p>
        <span class="username"><%= answer.author.username %></span>
          <span class="timestamp"><%= answer.created_at %></span>
          <span class="votes"># votes</span>
      </p>
      <hr>
      <p><%= answer.content %></p>
  <p>
  <% if answer.author_id == session[:user_id] %>
    <br>
    <div><%= link_to 'Edit', edit_answer_path(answer) %></div>
    <br>
  <% end %>
  <p>
  </li>

app/views/questions/_info.html.erb
  <li class="question-display">
      <p>
        <span class="username"><%= question.author.username %></span>
          <span class="timestamp"><%= question.created_at %></span>
          <%= render partial: "questions/votes", locals: {question: question} %>
      </p>
      <hr>
        <p><%= link_to question.title, question_path(question) %><p>
  <div class="edit">
  <% if question.author_id == session[:user_id] %>
  <p><%= link_to 'Edit', edit_question_path(question) %></p>
<% end %>
</div>
  </li>

app/views/questions/_river.html.erb
<% @questions.each do |question| %>
    <%= render partial: "questions/info", locals: {question: question} %>
<% end %>

app/views/questions/_votes.html.erb
<div class="vote">
  <%= form_for question, url: questions_upvote_path, method: :post, html: {class: "upvote_question"} do |f| %>
    <input type="image" src="<%= image_path("upArrow.png") %>" alt="submit"/>
    <input type="hidden" name="id" value="<%= question.id %>"/>
  <% end %>
  <%= form_for question, url: questions_downvote_path, method: :post, html: {class: "downvote_question"} do |f| %>
    <input type="image" src="<%= image_path("downArrow.png") %>" alt="submit"/>
    <input type="hidden" name="id" value="<%= question.id %>"/>
  <% end %>
    <span class="votes_count">
    <%= question.votes_count %>
  </span>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= form_for :question, url: question_path(@question), method: :patch, :html => {:class =>"dark-matter"} do |f| %>
  <%= render partial: "/errors" %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>

    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Destroy', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="question-list">
	<hr class="top">
	<div class="question-header">
		<h1>Questions</h1>
		<div class="order-by">
			<span><%= link_to "recent", questions_recent_path, class: "sort_link" %></span>
			<span><%= link_to "trending", questions_trending_path, class: "sort_link" %></span>
			<span><%= link_to "most votes", questions_most_votes_path, class: "sort_link" %></span>
		</div>
	</div>
	<hr class="bottom">
	<ul class="question-river">
		<% @questions.each do |question| %>
		<%= render partial: "questions/info", locals: {question: question} %>
		<% end %>
	</ul>
</div>

app/views/questions/new.html.erb
<%= form_for @question, :html => {:class =>"dark-matter"} do |f| %>
  <%= render partial: "/errors" %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>

    <%= f.submit %>
  </p>
<% end %>

app/views/questions/river.html.erb
<ul class="question-river">
  <% @questions.each do |question| %>
      <%= render partial: "questions/info", locals: {question: question} %>
  <% end %>
</ul>

app/views/questions/show.html.erb
<div class="question-list">
	<div class="comment_handler">
	<%= render partial: "questions/info", locals: {question: @question} %>
		<p class="comment_options question_comment"><%= link_to 'Add a comment', {controller: 'comments', action: 'new', type: 'Question', id: @question}, class: "add_comment" %></p>
</div>
		
	<ul class="comments">
		<% @question.comments.each do |comment| %>
		<%= render partial: "comments/show", locals: {comment: comment} %>
		<% end %>
	</ul>
	<hr class="top">
	<h2 class="answers-header"><%= @question.answers.count %> Answers</h2>
	<hr class="bottom">
	<ul>
		<% @question.answers.each do |answer| %>
		<%= render partial: "answers/show", locals: {answer: answer} %>
		<ul class="comments">
			<% answer.comments.each do |comment| %>
			<%= render partial: "comments/show", locals: {comment: comment} %>
			<% end %>
		</ul>
		<% end %>
	</ul>

	<div class="back">
		<%= link_to 'Back', questions_path %>
	</div>

	<%= render partial: "answers/new", locals: {answer: @answer} %>
</div>