config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  get '/questions/recent' => 'questions#recent'
  get '/questions/trending' => 'questions#trending'
  get '/questions/most_votes' => 'questions#index'

  resources :questions
  resources :comments
  resources :answers

  resources :users
  post '/users/login' => 'users#login'
  delete '/users/logout' => 'users#logout'

  post '/questions/upvote' => 'questions#upvote'
  post '/questions/downvote' => 'questions#downvote'

  post '/answers/upvote' => 'answers#upvote'
  post '/answers/downvote' => 'answers#downvote'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  validates_presence_of :content
  def associated_question
    case self.commentable_type
    when "Answer"
      self.commentable.question
    when "Question"
      self.commentable
    when "Comment"
      self.commentable.associated_question
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper
  def new
    @comment = Comment.new
    @type = case params[:type]
              when "Answer"
                Answer.find_by(id: params[:id])
              when "Question"
                Question.find_by(id: params[:id])
              when "Comment"
                Comment.find_by(id: params[:id])
              end
  end

  def create
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    commentable  = case params[:type]
                   when "Answer"
                    Answer.find_by(id: params[:id])
                   when "Question"
                    Question.find_by(id: params[:id])
                   when "Comment"
                    Comment.find_by(id: params[:id])
                   end
    attributes = comment_params.merge(author_id: session[:user_id])
    @comment = commentable.comments.build(attributes)
    @question = @comment.associated_question
    flash[:error] = "incorrect comment format" unless @comment.save
    if request.xhr?
      render partial: "comments/show", locals: {comment: @comment} 
    else
      redirect_to @question
    end
  end

  def edit
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    @comment = Comment.find_by(id: params[:id])
    @question = @comment.associated_question

    if @comment.author_id != session[:user_id]
      flash[:error] = "you are not the author of this comment"
      redirect_to @question
    end
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @question = @comment.associated_question
    @comment.update_attributes(comment_params)

    if @comment.save
      redirect_to @question
    else
      flash[:error] = "incorrect comment format"
      redirect_to edit_comment_url(@comment)
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    redirect_to question_url(@comment.question)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :author_id)
  end

end

app/views/comments/_show.html.erb
  <% if comment.commentable_type == "Comment" %>
    <div class="comment_handler subcomment">
      <% else %>
      <div class="comment_handler">
      <% end %>
  <li class="comment-display">
      <p>
        <span class="username"><%= comment.author.username %></span>
          <span class="timestamp"><%= comment.created_at %></span>
      </p>
      <hr>
      <p><%= comment.content %></p>
  <p class ="comment_options"><% if comment.author_id == session[:user_id] %>
  <%= link_to 'Edit', edit_comment_path(comment) %>
<% end %>
<%= link_to 'Add a comment', {controller: 'comments', action: 'new', type: 'Comment', id: comment.id}, class: "add_comment" %> </p>
  </li>
  <div class="subcomments">
  </div>
  <% comment.comments.each do |subComment| %>
      <%= render partial: "comments/show", locals: {comment: subComment} %>
      <% end %>
    </div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for :comment, url: comment_path(@comment), method: :patch, :html => {:class =>"dark-matter"} do |f| %>
  <%= render partial: "/errors" %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Destroy', comment_path(@comment), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', questions_path %>

app/views/comments/new.html.erb
<div class="comment_div">
<%= form_for @comment, :html => {:class => "dark-matter comment_form"} do |f| %>
  <%= render partial: "/errors" %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
    <input name="type" type="hidden" value="<%= @type.class %>" />
    <input name="id" type="hidden" value="<%= @type.id %>" />
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>