config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  get '/questions/recent' => 'questions#recent'
  get '/questions/trending' => 'questions#trending'
  get '/questions/most_votes' => 'questions#index'

  resources :questions
  resources :comments
  resources :answers

  resources :users
  post '/users/login' => 'users#login'
  delete '/users/logout' => 'users#logout'

  post '/questions/upvote' => 'questions#upvote'
  post '/questions/downvote' => 'questions#downvote'

  post '/answers/upvote' => 'answers#upvote'
  post '/answers/downvote' => 'answers#downvote'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :username, :password
  validates_uniqueness_of :username
  validates :password, length: { minimum: 6 }

  has_many :questions, :foreign_key => :author_id
  has_many :answers, :foreign_key => :author_id
  has_many :comments, :foreign_key => :author_id
  has_many :votes, :foreign_key => :user_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  def index # login page
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create # POST
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_url(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def login # POST
    @user = User.find_by(username: params[:user][:username]).try(:authenticate, params[:user][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_url(@user)
    else
      flash[:error] = 'incorrect username or password'
      redirect_to users_path
    end
  end

  def show # profile
    if !logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    @user = User.find_by(id: session[:user_id]) #check a better way to do this
  end

  def destroy # logout
    if current_user
      session.clear
    end
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/views/users/index.html.erb
<%= form_for :user, url: users_login_path, :html => {:class =>"dark-matter"}  do |f| %>
  <h1>User Login</h1>
  <%= f.text_field :username, placeholder: "username" %>
  <br><br>
  <%= f.password_field :password, placeholder: "password" %>
  <br><br>
  <hr>
  <br><br>
  <%= submit_tag("Login", :class =>"button") %>
  <br><br>
  <%= render partial: "/errors" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, :html => {:class =>"dark-matter"} do |f| %>
  <h1>New User Registration</h1>
  <%= f.text_field :username, placeholder: "username" %>
  <br><br>
  <%= f.password_field :password, placeholder: "password" %>
  <br><br>
  <hr>
  <br><br>
  <%= submit_tag("Register", :class =>"button")%>
  <br><br>
  <%= render partial: "/errors" %>
<% end %>

app/views/users/show.html.erb
<span class="create-question"><%= link_to 'Create a Question', new_question_path %></span>
<div class="users-questions">
  <hr class="top">
  <h1>Your Questions</h1>
  <hr class="bottom">
  <ul class="question-river">
    <% @user.questions.each do |question| %>
        <%= render partial: "questions/info", locals: {question: question} %>
    <% end %>
  </ul>
</div>