config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  get '/questions/recent' => 'questions#recent'
  get '/questions/trending' => 'questions#trending'
  get '/questions/most_votes' => 'questions#index'

  resources :questions
  resources :comments
  resources :answers

  resources :users
  post '/users/login' => 'users#login'
  delete '/users/logout' => 'users#logout'

  post '/questions/upvote' => 'questions#upvote'
  post '/questions/downvote' => 'questions#downvote'

  post '/answers/upvote' => 'answers#upvote'
  post '/answers/downvote' => 'answers#downvote'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Voteable
  belongs_to :question
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  validates_presence_of :content
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController

  def create
    @question = Question.find_by(id: params[:id])
    @answer = @question.answers.build(answer_params)
    @answer.author = current_user

    if @answer.save
      redirect_to @question
    else
      flash[:error] = "incorrect answer format"
      redirect_to @question
    end
  end

  def edit
    @answer = Answer.find_by(id: params[:id])
    if @answer.author == current_user
      render edit_answer_path
    else
      flash[:error] = "you are not the author of this answer"
      redirect_to @question
    end
  end

  def update
    @answer = Answer.find_by(id: params[:id])
    @answer.assign_attributes(answer_params)
    if @answer.save
      redirect_to question_url(@answer.question)
    else
      flash[:error] = "incorrect answer format"
      redirect_to edit_answer_url(@answer)
    end
  end

  def destroy
    @answer = Answer.find_by(id: params[:id])
    @answer.destroy
    redirect_to question_url(@answer.question)
  end

private

def answer_params
 params.require(:answer).permit(:content)
end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include ApplicationHelper

  def create
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    @question = Question.find_by(id: params[:id])
    @answer = @question.answers.build(answer_params)
    @answer.author_id = current_user.id

    flash[:error] = @answer.errors.full_messages unless @answer.save
    redirect_to @question
  end

  def edit
    unless logged_in?
      flash[:error] = "You must be logged in to do that!"
      redirect_to users_path
      return
    end
    @answer = Answer.find_by(id: params[:id])
    @question = @answer.question
    if @answer.author_id != current_user.id
      flash[:error] = "you are not the author of this answer"
      redirect_to @question
    end
  end

  def update
    @answer = Answer.find_by(id: params[:id])
    @question = @answer.question

    @answer.update_attributes(answer_params)
    if @answer.save
      redirect_to @question
    else
      flash[:error] = @answer.errors.full_messages
      redirect_to edit_answer_url(@answer)
    end
  end

  def destroy
    @answer = Answer.find_by(id: params[:id])
    @answer.destroy
    redirect_to question_url(@answer.question)
  end

  def upvote
    @answer = Answer.find_by(id: params[:id])
    unless @answer.voted_by_current_user?(voter: current_user, up: true)
      @answer.upvote(session[:user_id]) if logged_in?
    end
    unless request.xhr?
      redirect_to :back unless request.xhr?
    else
      render partial: "questions/votes", locals: {question: @answer.question}
    end
  end

  def downvote
    @answer = Answer.find_by(id: params[:id])
    unless @answer.voted_by_current_user?(voter: current_user, up: false) 
      @answer.downvote(session[:user_id]) if logged_in?
    end
    unless request.xhr?
      redirect_to :back unless request.xhr?
    else
      render partial: "questions/votes", locals: {question: @answer.question}
    end
  end


  private

  def answer_params
   params.require(:answer).permit(:content)
  end

  def vote_params
    params.require(:vote).permit(:up_or_down)
  end

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/views/answers/_new.html.erb
<%= form_for @answer, :html => {:class =>"dark-matter"} do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
    <input type="hidden" name="id" value="<%= @question.id %>"/>
  </p>

  <p>
    <%= f.submit "Post Your Answer" %>
  </p>
<% end %>

app/views/answers/_show.html.erb
  <div class="comment_handler">
  <li class="answer-display">
      <p>
        <span class="username"><%= answer.author.username %></span>
          <span class="timestamp"><%= answer.created_at %></span>
          <span class="votes"><%= render partial: "answers/votes", locals: {answer: answer} %></span>
      </p>
      <hr>
      <p><%= answer.content %></p>
  <p>
<p class="comment_options"><%= link_to 'Add a comment', {controller: 'comments', action: 'new', type: 'Answer', id: answer.id}, class: "add_comment" %>
    <div class="edit">
  <% if answer.author_id == session[:user_id] %>
    <div><%= link_to 'Edit', edit_answer_path(answer) %></div>
  <% end %>
  </p>
  </div>
  </li>
</div>

app/views/answers/_votes.html.erb
<div class="vote">
  <%= form_for answer, url: answers_upvote_path, method: :post, html: {class: "upvote_answer"} do |f| %>
    <input type="image" src="<%= image_path("upArrow.png") %>" alt="submit"/>
    <input type="hidden" name="id" value="<%= answer.id %>"/>
  <% end %>
  <%= form_for answer, url: answers_downvote_path, method: :post, html: {class: "downvote_answer"} do |f| %>
    <input type="image" src="<%= image_path("downArrow.png") %>" alt="submit"/>
    <input type="hidden" name="id" value="<%= answer.id %>"/>
  <% end %>
    <span class="votes_count">
    <%= answer.votes_count %>
  </span>
</div>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= form_for @answer, url: answer_path(@answer), method: :patch, :html => {:class =>"dark-matter"} do |f| %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Destroy', answer_path(@answer), method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Answer#index</h1>
<p>Find me in app/views/answer/index.html.erb</p>